/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author Risfianoor
 */
public class AplikasiPenampilGambar extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AplikasiPenampilGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonpanel = new javax.swing.JPanel();
        spongebob = new javax.swing.JButton();
        plankton = new javax.swing.JButton();
        patrick = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        imagepanel = new javax.swing.JPanel();
        gmbr1 = new javax.swing.JLabel();
        gmbr2 = new javax.swing.JLabel();
        gmbr3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonpanel.setBackground(new java.awt.Color(102, 255, 204));

        spongebob.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        spongebob.setText("Spongebob");
        spongebob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spongebobActionPerformed(evt);
            }
        });
        buttonpanel.add(spongebob);

        plankton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plankton.setText(" Plankton");
        plankton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planktonActionPerformed(evt);
            }
        });
        buttonpanel.add(plankton);

        patrick.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patrick.setText("Patrick");
        patrick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patrickActionPerformed(evt);
            }
        });
        buttonpanel.add(patrick);

        keluar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        buttonpanel.add(keluar);

        imagepanel.setLayout(new java.awt.CardLayout());

        gmbr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gmbr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/spongebob.png"))); // NOI18N
        gmbr1.setToolTipText("");
        gmbr1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagepanel.add(gmbr1, "1");

        gmbr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gmbr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/plankton.jpg"))); // NOI18N
        gmbr2.setToolTipText("");
        gmbr2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagepanel.add(gmbr2, "2");

        gmbr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gmbr3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/patrick.png"))); // NOI18N
        gmbr3.setToolTipText("");
        gmbr3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagepanel.add(gmbr3, "3");

        buttonpanel.add(imagepanel);

        getContentPane().add(buttonpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spongebobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spongebobActionPerformed
        CardLayout cl = (CardLayout)(imagepanel.getLayout());
        cl.show(imagepanel, "1");
    }//GEN-LAST:event_spongebobActionPerformed

    private void planktonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planktonActionPerformed
        CardLayout cl = (CardLayout)(imagepanel.getLayout());
        cl.show(imagepanel, "2");
    }//GEN-LAST:event_planktonActionPerformed

    private void patrickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patrickActionPerformed
        CardLayout cl = (CardLayout)(imagepanel.getLayout());
        cl.show(imagepanel, "3");
    }//GEN-LAST:event_patrickActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenampilGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JLabel gmbr1;
    private javax.swing.JLabel gmbr2;
    private javax.swing.JLabel gmbr3;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JButton keluar;
    private javax.swing.JButton patrick;
    private javax.swing.JButton plankton;
    private javax.swing.JButton spongebob;
    // End of variables declaration//GEN-END:variables
}
